Repository ita-social-projects/GreenCity, pull requests merged in 2019-09, with the labels that each got.

#119 #81 security
  pom.xml
  src/main/java/greencity/config/JwtConfig.java
  src/main/java/greencity/config/ScheduleConfig.java
  src/main/java/greencity/config/SecurityConfig.java
  src/main/java/greencity/controller/UserOwnSecurityController.java
  src/main/java/greencity/dto/userownsecurity/AccessTokenDto.java
  src/main/java/greencity/dto/userownsecurity/UserRegisterDto.java
  src/main/java/greencity/dto/userownsecurity/UserSignInDto.java
  src/main/java/greencity/dto/userownsecurity/UserSuccessSignInDto.java
  src/main/java/greencity/entity/UserOwnSecurity.java
  src/main/java/greencity/entity/VerifyEmail.java
  src/main/java/greencity/exception/BadEmailException.java
  src/main/java/greencity/exception/BadEmailOrPasswordException.java
  src/main/java/greencity/exception/BadIdException.java
  src/main/java/greencity/exception/BadRefreshTokenException.java
  src/main/java/greencity/exception/BadTokenException.java
  src/main/java/greencity/exception/BadUserException.java
  src/main/java/greencity/exception/UserActivationEmailTokenExpiredException.java
  src/main/java/greencity/exception/ValidationExceptionDto.java
  src/main/java/greencity/repository/UserOwnSecurityRepo.java
  src/main/java/greencity/repository/VerifyEmailRepo.java
  src/main/java/greencity/security/JwtFilter.java
  src/main/java/greencity/security/JwtTokenTool.java
  src/main/java/greencity/security/JwtUser.java
  src/main/java/greencity/service/UserOwnSecurityService.java
  src/main/java/greencity/service/UserService.java
  src/main/java/greencity/service/VerifyEmailService.java
  src/main/java/greencity/service/impl/UserOwnSecurityServiceImpl.java
  src/main/java/greencity/service/impl/UserServiceImpl.java
  src/main/java/greencity/service/impl/VerifyEmailServiceImpl.java
  src/main/resources/application.properties
  src/test/java/greencity/security/JwtFilterTest.java
  src/test/java/greencity/security/JwtTokenToolTest.java
  src/test/java/greencity/security/JwtUserDetailServiceTest.java
  src/test/java/greencity/security/JwtUserTest.java
  src/test/java/greencity/service/impl/UserOwnSecurityServiceImplTest.java
  src/test/java/greencity/service/impl/VerifyEmailServiceImplTest.java
  src/test/resources/application-dev.properties
  src/test/resources/application.properties
Labels: back-end

#127 Heroku deploy
  Procfile
  pom.xml
  src/main/java/greencity/constant/AppConstant.java
  src/main/java/greencity/controller/UserOwnSecurityController.java
  src/main/java/greencity/exception/CustomExceptionHandler.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/liquibase.properties
  src/test/java/greencity/service/impl/UserServiceImplTest.java
Labels: back-end, deploy

#160 Filtering
  src/main/java/greencity/config/SecurityConfig.java
  src/main/java/greencity/controller/PlaceController.java
  src/main/java/greencity/dto/category/CategoryDto.java
  src/main/java/greencity/dto/filter/FilterDiscountDto.java
  src/main/java/greencity/dto/filter/FilterPlaceDto.java
  src/main/java/greencity/entity/Discount.java
  src/main/java/greencity/entity/Place.java
  src/main/java/greencity/repository/PlaceRepo.java
  src/main/java/greencity/repository/options/PlaceFilter.java
  src/main/java/greencity/service/PlaceService.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/changelog/db.changelog-output-1.0.4.xml
Labels: Unregistered user, back-end, pri: high, type: subtask

#188 #156 filtering places by distance from user
  src/main/java/greencity/constant/AppConstant.java
  src/main/java/greencity/constant/ValidationConstants.java
  src/main/java/greencity/dto/filter/FilterDistanceDto.java
  src/main/java/greencity/dto/filter/FilterPlaceDto.java
  src/main/java/greencity/repository/options/PlaceFilter.java
  src/main/java/greencity/security/dto/ownsecurity/OwnSignUpDto.java
  src/main/java/greencity/security/jwt/JwtTokenTool.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
Labels: Bug, back-end, pri: medium, type: subtask

#191 #150_Filtering
  src/main/java/greencity/constant/AppConstant.java
  src/main/java/greencity/constant/ErrorMessage.java
  src/main/java/greencity/dto/filter/FilterPlaceDto.java
  src/main/java/greencity/exception/CustomExceptionHandler.java
  src/main/java/greencity/repository/options/PlaceFilter.java
Labels: Unregistered user, back-end, pri: high, type: subtask
