Repository ita-social-projects/GreenCity, pull requests merged in 2019-08, with the labels that each got.

#16 #6 add checkstyle config
  checkstyle/greenCity_checkstyle.xml
  checkstyle/img/1.png
  checkstyle/img/2.png
  checkstyle/img/3.png
  checkstyle/img/4.png
  checkstyle/img/5.png
  checkstyle/img/6.png
  checkstyle/img/7.png
  pom.xml
  src/main/java/greencity/GreenCityApplication.java
Labels: pri: medium, technical tasks

#19 #5 Add logger configuration
  src/main/java/greencity/GreenCityApplication.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: technical tasks

#32 #6 add more rules to checkstyle
  checkstyle/greenCity_checkstyle.xml
Labels: pri: medium, technical tasks

#64 #24 services mapper
  src/main/java/greencity/dto/location/LocationDto.java
  src/main/java/greencity/dto/openhours/OpenHoursDto.java
  src/main/java/greencity/dto/place/AdminPlaceDto.java
  src/main/java/greencity/dto/user/PlaceAuthorDto.java
  src/main/java/greencity/entity/Location.java
  src/main/java/greencity/entity/OpeningHours.java
  src/main/java/greencity/entity/Place.java
  src/main/java/greencity/entity/User.java
  src/main/java/greencity/entity/UserOwnSecurity.java
  src/main/java/greencity/entity/VerifyEmail.java
  src/main/java/greencity/mapping/AdminPlaceMapper.java
  src/main/java/greencity/repository/OpenHoursRepo.java
  src/main/java/greencity/repository/PlaceRepo.java
  src/main/java/greencity/repository/UserOwnSecurityRepo.java
  src/main/java/greencity/service/OpenHoursService.java
  src/main/java/greencity/service/PlaceService.java
  src/main/java/greencity/service/impl/OpenHoursServiceImpl.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/main/resources/application.properties
  src/test/java/greencity/GreenCityApplicationTests.java
Labels: Admin, back-end, pri: high, type: subtask

#76 #65 create user status enum and change logic for ban/block
  src/main/java/greencity/dto/PageableDto.java
  src/main/java/greencity/repository/UserRepo.java
  src/main/java/greencity/service/UserService.java
  src/main/java/greencity/service/impl/UserServiceImpl.java
  src/test/java/greencity/service/impl/UserServiceImplTest.java
Labels: Admin, back-end

#77 #42 opening hours category location repo service tests
  src/main/java/greencity/constant/ErrorMessage.java
  src/main/java/greencity/constant/LogMessage.java
  src/main/java/greencity/service/CategoryService.java
  src/main/java/greencity/service/LocationService.java
  src/main/java/greencity/service/OpenHoursService.java
  src/main/java/greencity/service/impl/CategoryServiceImpl.java
  src/main/java/greencity/service/impl/LocationServiceImpl.java
  src/main/java/greencity/service/impl/OpenHoursServiceImpl.java
  src/test/java/greencity/service/impl/CategoryServiceImplTest.java
  src/test/java/greencity/service/impl/LocationServiceImplTest.java
  src/test/java/greencity/service/impl/OpeningHoursServiceImplTest.java
Labels: back-end, type: subtask

#78 #46 move messages to constant, add tests for updateStatus()
  src/main/java/greencity/constant/AppConstant.java
  src/main/java/greencity/constant/ErrorMessage.java
  src/main/java/greencity/constant/LogMessage.java
  src/main/java/greencity/constant/ValidationConstants.java
  src/main/java/greencity/controller/AdminController.java
  src/main/java/greencity/dto/place/PlaceStatusDto.java
  src/main/java/greencity/exception/PlaceStatusException.java
  src/main/java/greencity/service/PlaceService.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/test/java/greencity/service/impl/PlaceServiceImplTest.java
Labels: Admin, back-end

#82 #24 controller
  src/main/java/greencity/dto/category/CategoryDto.java
  src/main/java/greencity/dto/openhours/OpenHoursDto.java
  src/main/java/greencity/dto/place/AdminPlaceDto.java
  src/main/java/greencity/entity/OpeningHours.java
  src/main/java/greencity/entity/Place.java
  src/main/java/greencity/entity/User.java
  src/main/java/greencity/repository/PlaceRepo.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/test/java/greencity/service/impl/PlaceServiceImplTest.java
  src/test/resources/application.properties
Labels: Admin, back-end

#75 #43 add list of cafes near the map
  src/main/java/greencity/controller/CategoryController.java
  src/main/java/greencity/controller/PlaceController.java
  src/main/java/greencity/dto/location/MapBoundsDto.java
  src/main/java/greencity/dto/place/PlaceByBoundsDto.java
  src/main/java/greencity/entity/User.java
  src/main/java/greencity/entity/enums/PlaceStatus.java
  src/main/java/greencity/exception/CustomExceptionHandler.java
  src/main/java/greencity/repository/PlaceRepo.java
  src/main/java/greencity/service/PlaceService.java
  src/main/java/greencity/service/impl/CategoryServiceImpl.java
  src/main/java/greencity/service/impl/LocationServiceImpl.java
  src/main/java/greencity/service/impl/OpenHoursServiceImpl.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/main/resources/application.properties
  src/test/java/greencity/service/impl/PlaceServiceImplTest.java
Labels: back-end, type: subtask

#90 Move input, output data to DTO in changePlaceStatus method
  pom.xml
  src/main/java/greencity/controller/AdminController.java
  src/main/java/greencity/controller/PlaceController.java
  src/main/java/greencity/dto/place/PlaceStatusDto.java
  src/main/java/greencity/service/PlaceService.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/main/java/greencity/util/DateTimeService.java
  src/test/java/greencity/service/impl/PlaceServiceImplTest.java
Labels: Admin, back-end, type: subtask

#93 #24 controller
  src/main/java/greencity/controller/PlaceController.java
  src/main/java/greencity/dto/openhours/OpeningHoursDto.java
  src/main/java/greencity/dto/place/AdminPlaceDto.java
  src/main/java/greencity/repository/PlaceRepo.java
  src/main/java/greencity/service/PlaceService.java
  src/main/java/greencity/service/impl/PlaceServiceImpl.java
  src/test/java/greencity/service/impl/PlaceServiceImplTest.java
Labels: Admin, back-end, type: subtask

#95 #81 security
  pom.xml
  src/main/java/greencity/config/JwtConfig.java
  src/main/java/greencity/config/SecurityConfig.java
  src/main/java/greencity/constant/ErrorMessage.java
  src/main/java/greencity/controller/UserOwnSecurityController.java
  src/main/java/greencity/dto/user_own_security/UserRegisterDto.java
  src/main/java/greencity/dto/user_own_security/UserSuccessSignInDto.java
  src/main/java/greencity/exception/BadRefreshTokenException.java
  src/main/java/greencity/exception/CustomExceptionHandler.java
  src/main/java/greencity/security/JwtFilter.java
  src/main/java/greencity/security/JwtTokenTool.java
  src/main/java/greencity/security/JwtUser.java
  src/main/java/greencity/security/JwtUserDetailService.java
  src/main/java/greencity/service/UserOwnSecurityService.java
  src/main/java/greencity/service/UserService.java
  src/main/java/greencity/service/impl/UserOwnSecurityServiceImpl.java
  src/main/java/greencity/service/impl/UserServiceImpl.java
  src/main/java/greencity/service/impl/VerifyEmailServiceImpl.java
  src/main/resources/application.properties
Labels: back-end, pri: medium, type: subtask
