Repository ita-social-projects/GreenCity, pull requests merged in 2021-05, with the labels that each got.

#2776 Add column phone number to User
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/ch-add-column-phone-to-user-Struk.xml
Labels: Technical tasks, back-end, points: 2

#2813 Changes seventh previous day commit
  service-api/src/main/java/greencity/constant/AppConstant.java
Labels: Technical tasks, back-end, points: 1

#2823 Expired habits
  dao/src/main/java/greencity/enums/HabitAssignStatus.java
  dao/src/main/java/greencity/repository/HabitAssignRepo.java
  service/pom.xml
  service/src/main/java/greencity/config/ScheduleConfig.java
Labels: Achievements

#2829 Update ScheduleConfig.java
  service/src/main/java/greencity/config/ScheduleConfig.java
Labels: Bug
