Repository ita-social-projects/GreenCity, pull requests merged in 2021-06, with the labels that each got.

#2857 Deleted search in header, change color checkbox, change the indents o…
  core/src/main/resources/static/css/header.css
  core/src/main/resources/static/management/css/table_Modal_Pagination.css
  core/src/main/resources/templates/core/header.html
  core/src/main/resources/templates/core/management_user.html
Labels: Admin.Bugs

#2847 Add a new constraint DEFAULT_HABIT_IMAGE
  service-api/src/main/java/greencity/constant/AppConstant.java
  service/src/main/java/greencity/service/ManagementHabitServiceImpl.java
  service/src/test/java/greencity/service/ManagementHabitServiceImplTest.java
Labels: Bug

#2879 Expired habits fixes
  dao/src/main/java/greencity/repository/HabitAssignRepo.java
  service-api/src/main/java/greencity/enums/HabitAssignStatus.java
  service/src/main/java/greencity/config/ScheduleConfig.java
Labels: Bug

#2920 [GreenCity] Fix bug in CustomShoppingListItemController #2908
  core/src/main/java/greencity/controller/CustomShoppingListItemController.java
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service/src/main/java/greencity/service/CustomShoppingListItemServiceImpl.java
  service/src/test/java/greencity/service/CustomShoppingListItemServiceImplTest.java
Labels: Bug, back-end
