Repository ita-social-projects/GreenCity, pull requests merged in 2022-11, with the labels that each got.

#4717 [API][Add a comment]Adding a comment to an existing event #4667
  core/src/main/java/greencity/controller/EventCommentController.java
  service-api/src/main/java/greencity/client/RestClient.java
  service-api/src/test/java/greencity/client/RestClientTest.java
  service/src/main/java/greencity/service/EventCommentServiceImpl.java
  service/src/test/java/greencity/service/EventCommentServiceImplTest.java
Labels: back-end, API, GreenCity

#4737 [GreenCity] - Should fix controllers on GreenCity #4729
  core/src/main/java/greencity/config/SecurityConfig.java
  dao/src/main/java/greencity/repository/UserShoppingListItemRepo.java
Labels: back-end, Admin. Habits

#4740 [GreenCity] - add authority for method getEventsCreatedByUser(); #4739
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/test/java/greencity/controller/EventsControllerTest.java
Labels: back-end
