Repository ita-social-projects/GreenCity, pull requests merged in 2024-06, with the labels that each got.

#7193 Add endpoint to return all habit assigns of non current user
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/main/java/greencity/controller/HabitAssignController.java
  core/src/test/java/greencity/controller/HabitAssignControllerTest.java
  dao/src/main/java/greencity/repository/HabitAssignRepo.java
  service-api/src/main/java/greencity/dto/habit/HabitAssignPreviewDto.java
  service-api/src/main/java/greencity/dto/habit/HabitPreviewDto.java
  service-api/src/main/java/greencity/service/HabitAssignService.java
  service/src/main/java/greencity/mapping/HabitAssignPreviewDtoMapper.java
  service/src/main/java/greencity/service/HabitAssignServiceImpl.java
  service/src/test/java/greencity/mapping/HabitAssignPreviewDtoMapperTest.java
  service/src/test/java/greencity/service/HabitAssignServiceImplTest.java
Labels: back-end, All habits

#7196 Add endpoint to return all habit assigns of non current user
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/main/java/greencity/controller/HabitAssignController.java
  core/src/test/java/greencity/controller/HabitAssignControllerTest.java
  dao/src/main/java/greencity/repository/HabitAssignRepo.java
  service-api/src/main/java/greencity/service/HabitAssignService.java
  service/src/main/java/greencity/service/HabitAssignServiceImpl.java
  service/src/test/java/greencity/service/HabitAssignServiceImplTest.java
Labels: back-end, All habits

#7213 fix achievement user action count calculation
  service-api/src/main/java/greencity/constant/AppConstant.java
  service/src/main/java/greencity/achievement/AchievementCalculation.java
  service/src/test/java/greencity/ModelUtils.java
Labels: back-end, Bug, Achievements

#7222 Adds new endpoint to retrieve information about working days by friends habits
  core/src/main/java/greencity/config/SecurityConfig.java
  core/src/main/java/greencity/controller/HabitAssignController.java
  core/src/test/java/greencity/controller/HabitAssignControllerTest.java
  dao/src/main/java/greencity/repository/HabitAssignRepo.java
  service-api/src/main/java/greencity/constant/ErrorMessage.java
  service-api/src/main/java/greencity/dto/habit/HabitWorkingDaysDto.java
  service-api/src/main/java/greencity/service/HabitAssignService.java
  service/src/main/java/greencity/service/HabitAssignServiceImpl.java
  service/src/test/java/greencity/service/HabitAssignServiceImplTest.java
Labels: back-end, Habit's page

#7226 Edit positions authorities mapping for service manager
  dao/src/main/resources/db/changelog/db.changelog-master.xml
  dao/src/main/resources/db/changelog/logs/ch-delete-values-positions-authorities-mapping-Kizerov.xml
Labels: Bug

#7237 Fix method to check for unread notifications
  dao/src/main/java/greencity/repository/NotificationRepo.java
  service/src/main/java/greencity/service/UserNotificationServiceImpl.java
  service/src/test/java/greencity/service/UserNotificationServiceImplTest.java
Labels: Bug
